import '../../styles/globals.css';
import LayoutShell from '@/components/LayoutShell';
import { ReactQueryProvider } from "../../provider/ReactQueryProvider"

export const metadata = {
  title: 'Naraka Face Gallery',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi">
      <body>
        <ReactQueryProvider>
          <LayoutShell>
            {children}
          </LayoutShell>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
