import '../../styles/globals.css';
import LayoutShell from '@/components/LayoutShell';

export const metadata = {
  title: 'Naraka Face Gallery',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="vi">
      <body>
        <LayoutShell>{children}</LayoutShell>
      </body>
    </html>
  );
}
